package ejercicios4repaso;

import java.text.DateFormat;
import java.text.NumberFormat;
import java.util.Calendar;
import java.util.Random;

/**
 *
 * @author Javier García (javiergarbedo.es)
 */
public class DeporteTV extends javax.swing.JFrame {
    //Marcador de cada equipo
    byte numGoles1, numGoles2;
    //Aforos predefinidos de las distintas gradas
    final short AFORO_TRIBUNA = 8000;
    final short AFORO_PREFERENCIA = 10000;
    final short AFORO_NORTE = 5000;
    final short AFORO_SUR = 5000;
    //Precios predefinidos de las distintas gradas
    final float PRECIO_TRIBUNA = 30.00F;
    final float PRECIO_PREFERENCIA = 20.00F;
    final float PRECIO_NORTE = 15.00F;
    final float PRECIO_SUR = 15.00F;
    //Tiempos de posesión de cada equipo (milisegundos)
    long tiempoPosesionEq1, tiempoPosesionEq2;
    Calendar calendarInicioPosesionActual = Calendar.getInstance();
    Calendar calendarInicioPosesionAnterior = Calendar.getInstance();
    byte equipoPosesion; //Último equipo que ha tenido la posesión 0, 1 o 2
    
    /**
     * Creates new form MainFrame
     */
    public DeporteTV() {
        initComponents();
        
        //Evitar que el usuario pueda cambiar el tamaño de la pantalla para que
        //  no se desajuste la imagen de TV
        setResizable(false);
        
        //Quitar inicialmente de la pantalla los paneles informativos
        jLabelTVAbajo.setVisible(false);
        
        //Ocultar inicialmente el reloj e iniciarlo en 0:0:0
        jgBeanClock1.setVisible(false);
        jgBeanClock1.stop();
        
        //Mostrar relojes de posesión a 0
        Calendar calendarMostrar = Calendar.getInstance();
        calendarMostrar.set(Calendar.HOUR_OF_DAY, 0); //Poner reloj a 0
        calendarMostrar.set(Calendar.MINUTE, 0);
        calendarMostrar.set(Calendar.SECOND, 0);
        DateFormat formatoTiempo = DateFormat.getTimeInstance(DateFormat.MEDIUM);
        jLabelPosesionEq1.setText(formatoTiempo.format(calendarMostrar.getTime()));                
        jLabelPosesionEq2.setText(formatoTiempo.format(calendarMostrar.getTime()));                
        
        //Asignar valores predefinidos a los aforos y precios
        jTextFieldAforoTribuna.setText(String.valueOf(AFORO_TRIBUNA));
        jTextFieldAforoPreferencia.setText(String.valueOf(AFORO_PREFERENCIA));
        jTextFieldAforoNorte.setText(String.valueOf(AFORO_NORTE));
        jTextFieldAforoSur.setText(String.valueOf(AFORO_SUR));
        
        jTextFieldPrecioTribuna.setText(String.valueOf(PRECIO_TRIBUNA));
        jTextFieldPrecioPreferencia.setText(String.valueOf(PRECIO_PREFERENCIA));
        jTextFieldPrecioNorte.setText(String.valueOf(PRECIO_NORTE));
        jTextFieldPrecioSur.setText(String.valueOf(PRECIO_SUR));
        
        jTextFieldVentaTribuna.setText("0");
        jTextFieldVentaPreferencia.setText("0");
        jTextFieldVentaNorte.setText("0");
        jTextFieldVentaSur.setText("0");        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jButtonGol = new javax.swing.JButton();
        jLabelMarcador = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldNombreEqLocal = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldNombreEqVisitante = new javax.swing.JTextField();
        jPanel13 = new javax.swing.JPanel();
        jButtonPosesionEq1 = new javax.swing.JButton();
        jButtonPosesionEq2 = new javax.swing.JButton();
        jButtonPosesionEq3 = new javax.swing.JButton();
        jLabelPosesionEq1 = new javax.swing.JLabel();
        jLabelPosesionEq2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldAforoNorte = new javax.swing.JTextField();
        jTextFieldAforoSur = new javax.swing.JTextField();
        jTextFieldAforoPreferencia = new javax.swing.JTextField();
        jTextFieldAforoTribuna = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldPrecioNorte = new javax.swing.JTextField();
        jTextFieldPrecioSur = new javax.swing.JTextField();
        jTextFieldPrecioPreferencia = new javax.swing.JTextField();
        jTextFieldPrecioTribuna = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextFieldVentaNorte = new javax.swing.JTextField();
        jTextFieldVentaSur = new javax.swing.JTextField();
        jTextFieldVentaPreferencia = new javax.swing.JTextField();
        jTextFieldVentaTribuna = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        jLocaleChooser1 = new com.toedter.components.JLocaleChooser();
        jPanel3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jButtonRelojIniciar = new javax.swing.JButton();
        jButtonRelojParar = new javax.swing.JButton();
        jButtonRelojMostrar = new javax.swing.JButton();
        jButtonRelojOcultar = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jButtonOcultarPanelInferior = new javax.swing.JButton();
        jButtonMostrarMarcador = new javax.swing.JButton();
        jButtonMostrarTaquilla = new javax.swing.JButton();
        jButtonMostrarPosesion = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabelTVAbajo = new javax.swing.JLabel();
        jgBeanClock1 = new es.javiergarbedo.jgbeanclock.JgBeanClock();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(695, 530));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Marcador"));

        jButtonGol.setText("Gol aleatorio");
        jButtonGol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGolActionPerformed(evt);
            }
        });

        jLabelMarcador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMarcador.setText("0 - 0");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonGol)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelMarcador, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonGol)
                    .addComponent(jLabelMarcador))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Equipos"));

        jLabel2.setText("Equipo local:");

        jTextFieldNombreEqLocal.setColumns(20);
        jTextFieldNombreEqLocal.setText("Equipo1");

        jLabel3.setText("Equipo visitante:");

        jTextFieldNombreEqVisitante.setColumns(20);
        jTextFieldNombreEqVisitante.setText("Equipo2");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldNombreEqLocal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNombreEqVisitante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldNombreEqLocal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldNombreEqVisitante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder("Posesión Balón"));

        jButtonPosesionEq1.setText("Equipo Local");
        jButtonPosesionEq1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPosesionEq1ActionPerformed(evt);
            }
        });

        jButtonPosesionEq2.setText("Equipo Visitante");
        jButtonPosesionEq2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPosesionEq2ActionPerformed(evt);
            }
        });

        jButtonPosesionEq3.setText("Sin posesión");
        jButtonPosesionEq3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPosesionEq3ActionPerformed(evt);
            }
        });

        jLabelPosesionEq1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPosesionEq1.setText(" ");

        jLabelPosesionEq2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPosesionEq2.setText(" ");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabelPosesionEq1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonPosesionEq1, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonPosesionEq2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelPosesionEq2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonPosesionEq3, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPosesionEq1)
                    .addComponent(jButtonPosesionEq2)
                    .addComponent(jButtonPosesionEq3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPosesionEq1)
                    .addComponent(jLabelPosesionEq2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(460, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(220, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Eventos", jPanel1);

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Aforo"));

        jLabel4.setText("Tribuna:");

        jLabel5.setText("Preferencia:");

        jLabel6.setText("Fondo Sur:");

        jLabel7.setText("Fondo Norte:");

        jTextFieldAforoNorte.setColumns(5);

        jTextFieldAforoSur.setColumns(5);

        jTextFieldAforoPreferencia.setColumns(5);

        jTextFieldAforoTribuna.setColumns(5);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldAforoTribuna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldAforoPreferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldAforoSur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldAforoNorte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldAforoTribuna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldAforoPreferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldAforoSur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldAforoNorte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder("Precios"));

        jLabel8.setText("Tribuna:");

        jLabel9.setText("Preferencia:");

        jLabel10.setText("Fondo Sur:");

        jLabel11.setText("Fondo Norte:");

        jTextFieldPrecioNorte.setColumns(5);

        jTextFieldPrecioSur.setColumns(5);

        jTextFieldPrecioPreferencia.setColumns(5);

        jTextFieldPrecioTribuna.setColumns(5);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldPrecioTribuna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPrecioPreferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPrecioSur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPrecioNorte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldPrecioTribuna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextFieldPrecioPreferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextFieldPrecioSur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextFieldPrecioNorte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder("Entradas Vendidas"));

        jLabel12.setText("Tribuna:");

        jLabel13.setText("Preferencia:");

        jLabel14.setText("Fondo Sur:");

        jLabel15.setText("Fondo Norte:");

        jTextFieldVentaNorte.setColumns(5);

        jTextFieldVentaSur.setColumns(5);

        jTextFieldVentaPreferencia.setColumns(5);

        jTextFieldVentaTribuna.setColumns(5);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldVentaTribuna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldVentaPreferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldVentaSur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldVentaNorte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTextFieldVentaTribuna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTextFieldVentaPreferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jTextFieldVentaSur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jTextFieldVentaNorte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder("Idioma formato"));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLocaleChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLocaleChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(363, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(257, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Taquilla", jPanel2);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Reloj"));

        jButtonRelojIniciar.setText("Iniciar");
        jButtonRelojIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRelojIniciarActionPerformed(evt);
            }
        });

        jButtonRelojParar.setText("Parar");
        jButtonRelojParar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRelojPararActionPerformed(evt);
            }
        });

        jButtonRelojMostrar.setText("Mostrar");
        jButtonRelojMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRelojMostrarActionPerformed(evt);
            }
        });

        jButtonRelojOcultar.setText("Ocultar");
        jButtonRelojOcultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRelojOcultarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonRelojMostrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonRelojOcultar, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonRelojIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonRelojParar, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonRelojMostrar)
                    .addComponent(jButtonRelojOcultar)
                    .addComponent(jButtonRelojIniciar)
                    .addComponent(jButtonRelojParar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Panel Inferior"));

        jButtonOcultarPanelInferior.setText("Ocultar");
        jButtonOcultarPanelInferior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOcultarPanelInferiorActionPerformed(evt);
            }
        });

        jButtonMostrarMarcador.setText("Marcador");
        jButtonMostrarMarcador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMostrarMarcadorActionPerformed(evt);
            }
        });

        jButtonMostrarTaquilla.setText("Taquilla");
        jButtonMostrarTaquilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMostrarTaquillaActionPerformed(evt);
            }
        });

        jButtonMostrarPosesion.setText("Posesión");
        jButtonMostrarPosesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMostrarPosesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonOcultarPanelInferior, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonMostrarMarcador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonMostrarTaquilla, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonMostrarPosesion, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonOcultarPanelInferior)
                    .addComponent(jButtonMostrarMarcador)
                    .addComponent(jButtonMostrarTaquilla)
                    .addComponent(jButtonMostrarPosesion))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(457, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(337, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Mesa Control", jPanel3);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTVAbajo.setBackground(new java.awt.Color(102, 102, 102));
        jLabelTVAbajo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelTVAbajo.setForeground(new java.awt.Color(255, 255, 102));
        jLabelTVAbajo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTVAbajo.setText("jLabelTVAbajo");
        jLabelTVAbajo.setOpaque(true);
        jPanel4.add(jLabelTVAbajo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 695, -1));

        jgBeanClock1.setBackground(new java.awt.Color(102, 102, 102));
        jgBeanClock1.setForeground(new java.awt.Color(255, 255, 102));
        jgBeanClock1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jgBeanClock1.setOpaque(true);
        jPanel4.add(jgBeanClock1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ronaldo49.jpg"))); // NOI18N
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 695, 490));

        jTabbedPane1.addTab("Salida TV", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGolActionPerformed
        Random generadorGoles = new Random();
        //Generar aletoriamente el equipo que marca el gol. Si el resultado
        //  es true se considera que ha marcado el equipo 1, y en caso contrario
        //  (false) se considera que ha marcado el equipo 2
        boolean golEquipo1 = generadorGoles.nextBoolean();
        //Incrementar el número de goles al equipo correspondiente
        numGoles1 += golEquipo1 ? 1 : 0;
        //Si no es gol del equipo1, se incrementa al equipo2
        numGoles2 += !golEquipo1 ? 1 : 0;
        //Mostrar el resultado actual
        jLabelMarcador.setText(numGoles1 + " - " + numGoles2);
    }//GEN-LAST:event_jButtonGolActionPerformed

    private void jButtonOcultarPanelInferiorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOcultarPanelInferiorActionPerformed
        jLabelTVAbajo.setVisible(false);
    }//GEN-LAST:event_jButtonOcultarPanelInferiorActionPerformed

    private void jButtonMostrarMarcadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMostrarMarcadorActionPerformed
        jLabelTVAbajo.setVisible(true);
        String nombreEquipo1 = jTextFieldNombreEqLocal.getText();
        String nombreEquipo2 = jTextFieldNombreEqVisitante.getText();
        jLabelTVAbajo.setText(nombreEquipo1 + "   " + numGoles1 + " - "
                + numGoles2 + "   " + nombreEquipo2);        
    }//GEN-LAST:event_jButtonMostrarMarcadorActionPerformed

    private void jButtonRelojMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRelojMostrarActionPerformed
        //Mostrar el reloj en la salida TV
        jgBeanClock1.setVisible(true);
    }//GEN-LAST:event_jButtonRelojMostrarActionPerformed

    private void jButtonRelojOcultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRelojOcultarActionPerformed
        //Ocultar el reloj en la salida TV
        jgBeanClock1.setVisible(false);
    }//GEN-LAST:event_jButtonRelojOcultarActionPerformed

    private void jButtonRelojIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRelojIniciarActionPerformed
        //Iniciar el contador del reloj desde 0
        jgBeanClock1.start();
    }//GEN-LAST:event_jButtonRelojIniciarActionPerformed

    private void jButtonRelojPararActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRelojPararActionPerformed
        //Parar el contador del reloj
        jgBeanClock1.stop();
    }//GEN-LAST:event_jButtonRelojPararActionPerformed

    private void jButtonMostrarTaquillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMostrarTaquillaActionPerformed
        //Calcular el aforo total del estadio
        int aforoTribuna = Integer.valueOf(jTextFieldAforoTribuna.getText());
        int aforoPreferencia = Integer.valueOf(jTextFieldAforoPreferencia.getText());
        int aforoNorte = Integer.valueOf(jTextFieldAforoNorte.getText());
        int aforoSur = Integer.valueOf(jTextFieldAforoSur.getText());
        int aforoTotal = aforoTribuna + aforoPreferencia + aforoNorte + aforoSur;

        //Calular el número total de entradas vendidas
        int ventaTribuna = Integer.valueOf(jTextFieldVentaTribuna.getText());
        int ventaPreferencia = Integer.valueOf(jTextFieldVentaPreferencia.getText());
        int ventaNorte = Integer.valueOf(jTextFieldVentaNorte.getText());
        int ventaSur = Integer.valueOf(jTextFieldVentaSur.getText());
        int ventaTotal = ventaTribuna + ventaPreferencia + ventaNorte + ventaSur;

        //Obtener precios de cada categoría
        float precioTribuna = Float.valueOf(jTextFieldPrecioTribuna.getText());
        float precioPreferencia = Float.valueOf(jTextFieldPrecioPreferencia.getText());
        float precioNorte = Float.valueOf(jTextFieldPrecioNorte.getText());
        float precioSur = Float.valueOf(jTextFieldPrecioSur.getText());

        //Obtener porcentaje de aforo vendido
        float porcentajeAforoVendido = (float)ventaTotal / aforoTotal;
        float importeAforoVendido = ventaTribuna*precioTribuna + ventaPreferencia*precioPreferencia 
                + ventaNorte*precioNorte + ventaSur*precioSur;

        //Crear formatos de porcentaje y moneda según idioma seleccionado
        NumberFormat formatoPorcentaje = NumberFormat.getPercentInstance(jLocaleChooser1.getLocale());
        formatoPorcentaje.setMaximumFractionDigits(0);
        NumberFormat formatoMoneda = NumberFormat.getCurrencyInstance(jLocaleChooser1.getLocale());
        jLabelTVAbajo.setVisible(true);  
        jLabelTVAbajo.setText("Asistencia: " + formatoPorcentaje.format(porcentajeAforoVendido)
                + "    Taquilla: " + formatoMoneda.format(importeAforoVendido));  
    }//GEN-LAST:event_jButtonMostrarTaquillaActionPerformed

    private void jButtonPosesionEq1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPosesionEq1ActionPerformed
        //Calcular tiempo que ha durado la última posesión
        calendarInicioPosesionAnterior = calendarInicioPosesionActual;
        calendarInicioPosesionActual = Calendar.getInstance();
        long ultimoTiempoPosesion = calendarInicioPosesionActual.getTimeInMillis() - calendarInicioPosesionAnterior.getTimeInMillis();

        //Se aculuma el último tiempo de posesión al equipo que la tuviera
        tiempoPosesionEq2 += (equipoPosesion==2) ? ultimoTiempoPosesion : 0;

        //Se da la posesión al equipo 1
        equipoPosesion = 1;

        //Desactivar botón para que no se pueda repetir la pulsación
        jButtonPosesionEq1.setEnabled(false);
        jButtonPosesionEq2.setEnabled(true);  
        
        //Mostrar tiempo de posesión
        Calendar calendarMostrar = Calendar.getInstance();
        calendarMostrar.set(Calendar.HOUR_OF_DAY, 0); //Poner reloj a 0
        calendarMostrar.set(Calendar.MINUTE, 0);
        calendarMostrar.set(Calendar.SECOND, 0);
        //Sumar los segundos del tiempo al reloj en 0
        calendarMostrar.add(Calendar.SECOND, (int)tiempoPosesionEq2/1000);
        DateFormat formatoTiempo = DateFormat.getTimeInstance(DateFormat.MEDIUM, jLocaleChooser1.getLocale());
        jLabelPosesionEq2.setText(formatoTiempo.format(calendarMostrar.getTime()));
    }//GEN-LAST:event_jButtonPosesionEq1ActionPerformed

    private void jButtonPosesionEq2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPosesionEq2ActionPerformed
        //Calcular tiempo que ha durado la última posesión
        calendarInicioPosesionAnterior = calendarInicioPosesionActual;
        calendarInicioPosesionActual = Calendar.getInstance();
        long ultimoTiempoPosesion = calendarInicioPosesionActual.getTimeInMillis() - calendarInicioPosesionAnterior.getTimeInMillis();

        //Se aculuma el último tiempo de posesión al equipo que la tuviera
        tiempoPosesionEq1 += (equipoPosesion==1) ? ultimoTiempoPosesion : 0;

        //Se da la posesión al equipo 2
        equipoPosesion = 2;

        //Desactivar botón para que no se pueda repetir la pulsación
        jButtonPosesionEq2.setEnabled(false);        
        jButtonPosesionEq1.setEnabled(true);                
        
        //Mostrar tiempo de posesión
        Calendar calendarMostrar = Calendar.getInstance();
        calendarMostrar.set(Calendar.HOUR_OF_DAY, 0); //Poner reloj a 0
        calendarMostrar.set(Calendar.MINUTE, 0);
        calendarMostrar.set(Calendar.SECOND, 0);
        //Sumar los segundos del tiempo al reloj en 0
        calendarMostrar.add(Calendar.SECOND, (int)tiempoPosesionEq1/1000);
        DateFormat formatoTiempo = DateFormat.getTimeInstance(DateFormat.MEDIUM, jLocaleChooser1.getLocale());
        jLabelPosesionEq1.setText(formatoTiempo.format(calendarMostrar.getTime()));        
    }//GEN-LAST:event_jButtonPosesionEq2ActionPerformed

    private void jButtonPosesionEq3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPosesionEq3ActionPerformed
        calendarInicioPosesionAnterior = calendarInicioPosesionActual;
        calendarInicioPosesionActual = Calendar.getInstance();
        long ultimoTiempoPosesion = calendarInicioPosesionActual.getTimeInMillis() - calendarInicioPosesionAnterior.getTimeInMillis();
        //Se aculuma el último tiempo de posesión al equipo que la tuviera
        tiempoPosesionEq1 += (equipoPosesion==1) ? ultimoTiempoPosesion : 0;
        tiempoPosesionEq2 += (equipoPosesion==2) ? ultimoTiempoPosesion : 0;
        //Se quita la posesión de cualquier equipo
        equipoPosesion = 0;
        //Activar botones de posesión de ambos equipos
        jButtonPosesionEq2.setEnabled(true);        
        jButtonPosesionEq1.setEnabled(true);                        

        //Mostrar tiempo de posesión equipo 1
        Calendar calendarMostrar = Calendar.getInstance();
        calendarMostrar.set(Calendar.HOUR_OF_DAY, 0); //Poner reloj a 0
        calendarMostrar.set(Calendar.MINUTE, 0);
        calendarMostrar.set(Calendar.SECOND, 0);
        //Sumar los segundos del tiempo al reloj en 0
        calendarMostrar.add(Calendar.SECOND, (int)tiempoPosesionEq1/1000);
        DateFormat formatoTiempo = DateFormat.getTimeInstance(DateFormat.MEDIUM, jLocaleChooser1.getLocale());
        jLabelPosesionEq1.setText(formatoTiempo.format(calendarMostrar.getTime()));                
        
        //Mostrar tiempo de posesión equipo 2
        calendarMostrar.set(Calendar.HOUR_OF_DAY, 0); //Poner reloj a 0
        calendarMostrar.set(Calendar.MINUTE, 0);
        calendarMostrar.set(Calendar.SECOND, 0);
        //Sumar los segundos del tiempo al reloj en 0
        calendarMostrar.add(Calendar.SECOND, (int)tiempoPosesionEq2/1000);
        jLabelPosesionEq2.setText(formatoTiempo.format(calendarMostrar.getTime()));                        
    }//GEN-LAST:event_jButtonPosesionEq3ActionPerformed

    private void jButtonMostrarPosesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMostrarPosesionActionPerformed
        jLabelTVAbajo.setVisible(true);
        //Calcular porcentajes de posesión
        float porcenPosesionEq1 = (float)tiempoPosesionEq1 / (tiempoPosesionEq1 + tiempoPosesionEq2);
        float porcenPosesionEq2 = 1 - porcenPosesionEq1;
        //Crear formato de porcentaje
        NumberFormat formatoPorcentaje = NumberFormat.getPercentInstance(jLocaleChooser1.getLocale());
        //Mostrar datos de posesión de cada equipo
        String nombreEquipo1 = jTextFieldNombreEqLocal.getText();
        String nombreEquipo2 = jTextFieldNombreEqVisitante.getText();
        jLabelTVAbajo.setText("Posesión: " + nombreEquipo1 + " (" + formatoPorcentaje.format(porcenPosesionEq1) + ") "
                + nombreEquipo2 + " (" + formatoPorcentaje.format(porcenPosesionEq2) + ")");
    }//GEN-LAST:event_jButtonMostrarPosesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeporteTV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeporteTV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeporteTV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeporteTV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeporteTV().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGol;
    private javax.swing.JButton jButtonMostrarMarcador;
    private javax.swing.JButton jButtonMostrarPosesion;
    private javax.swing.JButton jButtonMostrarTaquilla;
    private javax.swing.JButton jButtonOcultarPanelInferior;
    private javax.swing.JButton jButtonPosesionEq1;
    private javax.swing.JButton jButtonPosesionEq2;
    private javax.swing.JButton jButtonPosesionEq3;
    private javax.swing.JButton jButtonRelojIniciar;
    private javax.swing.JButton jButtonRelojMostrar;
    private javax.swing.JButton jButtonRelojOcultar;
    private javax.swing.JButton jButtonRelojParar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelMarcador;
    private javax.swing.JLabel jLabelPosesionEq1;
    private javax.swing.JLabel jLabelPosesionEq2;
    private javax.swing.JLabel jLabelTVAbajo;
    private com.toedter.components.JLocaleChooser jLocaleChooser1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextFieldAforoNorte;
    private javax.swing.JTextField jTextFieldAforoPreferencia;
    private javax.swing.JTextField jTextFieldAforoSur;
    private javax.swing.JTextField jTextFieldAforoTribuna;
    private javax.swing.JTextField jTextFieldNombreEqLocal;
    private javax.swing.JTextField jTextFieldNombreEqVisitante;
    private javax.swing.JTextField jTextFieldPrecioNorte;
    private javax.swing.JTextField jTextFieldPrecioPreferencia;
    private javax.swing.JTextField jTextFieldPrecioSur;
    private javax.swing.JTextField jTextFieldPrecioTribuna;
    private javax.swing.JTextField jTextFieldVentaNorte;
    private javax.swing.JTextField jTextFieldVentaPreferencia;
    private javax.swing.JTextField jTextFieldVentaSur;
    private javax.swing.JTextField jTextFieldVentaTribuna;
    private es.javiergarbedo.jgbeanclock.JgBeanClock jgBeanClock1;
    // End of variables declaration//GEN-END:variables
}
